/* Language strings for Aarogya Setu MH — English, Hindi, Marathi */
const STR = {
  en: {
    title:"Aarogya Setu MH", sub:"Continuity of care, sub-centre to district hospital",
    abhaNotLinked:"ABHA: not linked", selectFacility:"📍 Select facility",
    largeText:"A+ Large text",
    tabs:{home:"Home",triage:"Triage",queue:"Queue",referral:"Referral",map:"Map",meds:"Meds",dash:"Dashboard"},
    home:{eyebrow:"Welcome", title:"What do you need today?",
      linkAbha:"Link your ABHA ID", abhaPh:"14-digit ABHA number",
      village:"Your nearest facility", link:"Link & continue",
      tiles:{triage:["🩺","Check symptoms","Speak or type"],
             video:["📹","Video consult","Talk to a doctor"],
             queue:["🎫","Book / Queue","Skip the travel"],
             referral:["🔗","My referral","Track your case"],
             map:["🗺️","Facility map","Find nearest centre"],
             meds:["💊","Medicine check","Is it in stock?"],
             followup:["❤️‍🩹","Follow-up","Maternal / child / chronic"]},
      recent:"Recent activity", noActivity:"No activity yet in this session."},
    triage:{eyebrow:"Digital triage", title:"Tell us what's wrong",
      voiceLabel:"Speak your problem (Marathi, Hindi or English)",
      voicePlaceholder:"Tap the mic and speak, or type here...",
      listening:"Listening… speak now", notSupported:"Voice input isn't supported in this browser. Please type instead.",
      detected:"We heard:", autoSelected:"Automatically selected from your voice:",
      symptomsLbl:"Select symptoms (multiple allowed)", durationLbl:"How long has this lasted?",
      severityLbl:"How severe does it feel? (1 = mild, 5 = worst)", ageLbl:"Age", ageGroupLbl:"Age group",
      submit:"Assess", result:"Assessment result",
      low:"Low risk — self-care advised", med:"Medium risk — teleconsultation recommended",
      high:"High risk — visit facility / emergency escalation",
      lowBody:"Home care and monitoring should be sufficient. Recheck if symptoms worsen.",
      medBody:"Book a teleconsultation with a PHC medical officer within 24 hours.",
      highBody:"This may need urgent attention. We've flagged this for emergency escalation and nearest facility referral.",
      bookConsult:"Book teleconsultation now", escalate:"Escalate to nearest facility",
      readAloud:"🔊 Read result aloud",
      durations:["<1 day","1-3 days","4-7 days",">1 week"],
      groups:["Child (0-12)","Adolescent (13-18)","Adult (19-59)","Senior (60+)"]},
    queue:{eyebrow:"Appointments & queue", title:"Book a slot, skip the line",
      facility:"Facility", dept:"Department", slot:"Preferred slot",
      book:"Book appointment", live:"Live queue status", token:"Your token",
      wait:"Estimated wait", position:"position in queue"},
    referral:{eyebrow:"Continuity of care", title:"Your referral journey",
      note:"This thread follows your case as it moves between facility tiers, so no record is lost in transit."},
    map:{eyebrow:"Facility map", title:"Health centres near you",
      legend:"Legend", tapHint:"Tap a marker for details, distance and quick actions.",
      subCentre:"Sub-Centre", phc:"PHC", ruralHospital:"Rural Hospital", districtHospital:"District Hospital",
      viewQueue:"Book / view queue", viewMeds:"Check medicine stock", coordinates:"Coordinates"},
    meds:{eyebrow:"Diagnostics & pharmacy", title:"Medicine & test availability",
      search:"Search medicine or test", nearby:"Nearby facilities"},
    dash:{eyebrow:"Facility dashboard", title:"Today at a glance",
      staffToggle:"Staff / admin view", triaged:"Patients triaged", highRisk:"High-risk pending",
      referralRate:"Referral completion", stockouts:"Medicines low/out",
      followupList:"High-risk follow-ups due", contacted:"Mark contacted"},
    sos:{title:"Emergency escalation", body:"This simulates an emergency alert to the nearest facility and ambulance dispatch (108).",
      nearest:"Nearest facility", call:"Call 108 (Ambulance)", alert:"Send facility alert", cancel:"Cancel"},
    toastLinked:"ABHA linked. Continuity record active.",
    toastBooked:"Appointment booked — token",
    toastAlert:"Emergency alert sent to facility ✓",
    toastContacted:"Marked as contacted",
    micDenied:"Microphone access denied. You can type your problem instead."
  },
  hi: {
    title:"आरोग्य सेतु MH", sub:"उप-केंद्र से जिला अस्पताल तक निरंतर देखभाल",
    abhaNotLinked:"ABHA: लिंक नहीं है", selectFacility:"📍 सुविधा चुनें",
    largeText:"A+ बड़े अक्षर",
    tabs:{home:"होम",triage:"जांच",queue:"कतार",referral:"रेफरल",map:"मानचित्र",meds:"दवा",dash:"डैशबोर्ड"},
    home:{eyebrow:"स्वागत है", title:"आज आपको क्या चाहिए?",
      linkAbha:"अपना ABHA ID लिंक करें", abhaPh:"14 अंकों का ABHA नंबर",
      village:"आपकी नज़दीकी सुविधा", link:"लिंक करें और आगे बढ़ें",
      tiles:{triage:["🩺","लक्षण जांचें","बोलें या लिखें"],
             video:["📹","वीडियो परामर्श","डॉक्टर से बात करें"],
             queue:["🎫","बुक करें / कतार","यात्रा से बचें"],
             referral:["🔗","मेरा रेफरल","अपना केस ट्रैक करें"],
             map:["🗺️","सुविधा मानचित्र","नज़दीकी केंद्र खोजें"],
             meds:["💊","दवा जांचें","स्टॉक में है क्या?"],
             followup:["❤️‍🩹","फॉलो-अप","मातृ / बाल / पुरानी बीमारी"]},
      recent:"हाल की गतिविधि", noActivity:"इस सत्र में अभी कोई गतिविधि नहीं।"},
    triage:{eyebrow:"डिजिटल ट्राइएज", title:"बताएं क्या तकलीफ है",
      voiceLabel:"अपनी समस्या बोलें (मराठी, हिंदी या अंग्रेज़ी)",
      voicePlaceholder:"माइक दबाएं और बोलें, या यहां टाइप करें...",
      listening:"सुन रहे हैं… अब बोलें", notSupported:"इस ब्राउज़र में आवाज़ इनपुट उपलब्ध नहीं है। कृपया टाइप करें।",
      detected:"हमने सुना:", autoSelected:"आपकी आवाज़ से स्वतः चुना गया:",
      symptomsLbl:"लक्षण चुनें (एक से अधिक चुन सकते हैं)", durationLbl:"यह कब से है?",
      severityLbl:"कितना गंभीर लगता है? (1=हल्का, 5=सबसे ज़्यादा)", ageLbl:"उम्र", ageGroupLbl:"आयु वर्ग",
      submit:"जांच करें", result:"जांच परिणाम",
      low:"कम जोखिम — घरेलू देखभाल पर्याप्त", med:"मध्यम जोखिम — टेलीपरामर्श सुझाया गया",
      high:"उच्च जोखिम — तुरंत सुविधा पर जाएं / आपातकालीन",
      lowBody:"घर पर देखभाल और निगरानी पर्याप्त होनी चाहिए। लक्षण बढ़ें तो दोबारा जांचें।",
      medBody:"24 घंटे के भीतर PHC चिकित्सा अधिकारी से टेलीपरामर्श बुक करें।",
      highBody:"इसे तुरंत ध्यान देने की आवश्यकता हो सकती है। हमने इसे आपातकालीन एस्केलेशन के लिए चिह्नित किया है।",
      bookConsult:"अभी टेलीपरामर्श बुक करें", escalate:"नज़दीकी सुविधा को सूचित करें",
      readAloud:"🔊 परिणाम सुनें",
      durations:["<1 दिन","1-3 दिन","4-7 दिन",">1 सप्ताह"],
      groups:["बच्चा (0-12)","किशोर (13-18)","वयस्क (19-59)","वरिष्ठ (60+)"]},
    queue:{eyebrow:"अपॉइंटमेंट व कतार", title:"स्लॉट बुक करें, कतार छोड़ें",
      facility:"सुविधा", dept:"विभाग", slot:"पसंदीदा समय",
      book:"अपॉइंटमेंट बुक करें", live:"लाइव कतार स्थिति", token:"आपका टोकन",
      wait:"अनुमानित प्रतीक्षा", position:"कतार में स्थान"},
    referral:{eyebrow:"निरंतर देखभाल", title:"आपकी रेफरल यात्रा",
      note:"यह धागा आपके केस को सुविधाओं के बीच ट्रैक करता है, ताकि कोई रिकॉर्ड न खोए।"},
    map:{eyebrow:"सुविधा मानचित्र", title:"आपके पास के स्वास्थ्य केंद्र",
      legend:"संकेत", tapHint:"विवरण, दूरी और त्वरित कार्रवाई के लिए मार्कर पर टैप करें।",
      subCentre:"उप-केंद्र", phc:"PHC", ruralHospital:"ग्रामीण अस्पताल", districtHospital:"जिला अस्पताल",
      viewQueue:"बुक करें / कतार देखें", viewMeds:"दवा स्टॉक जांचें", coordinates:"निर्देशांक"},
    meds:{eyebrow:"जांच व फार्मेसी", title:"दवा व टेस्ट उपलब्धता",
      search:"दवा या टेस्ट खोजें", nearby:"नज़दीकी सुविधाएं"},
    dash:{eyebrow:"सुविधा डैशबोर्ड", title:"आज की स्थिति",
      staffToggle:"स्टाफ / प्रशासन दृश्य", triaged:"जांचे गए मरीज़", highRisk:"उच्च जोखिम लंबित",
      referralRate:"रेफरल पूर्णता", stockouts:"दवाएं कम/समाप्त",
      followupList:"उच्च जोखिम फॉलो-अप देय", contacted:"संपर्क किया गया चिह्नित करें"},
    sos:{title:"आपातकालीन एस्केलेशन", body:"यह नज़दीकी सुविधा और एम्बुलेंस (108) को आपातकालीन अलर्ट भेजने का अनुकरण करता है।",
      nearest:"नज़दीकी सुविधा", call:"108 पर कॉल करें (एम्बुलेंस)", alert:"सुविधा अलर्ट भेजें", cancel:"रद्द करें"},
    toastLinked:"ABHA लिंक हो गया। निरंतर रिकॉर्ड सक्रिय।",
    toastBooked:"अपॉइंटमेंट बुक हुई — टोकन",
    toastAlert:"आपातकालीन अलर्ट सुविधा को भेजा गया ✓",
    toastContacted:"संपर्क किया गया चिह्नित",
    micDenied:"माइक्रोफ़ोन की अनुमति नहीं मिली। कृपया टाइप करें।"
  },
  mr: {
    title:"आरोग्य सेतू MH", sub:"उपकेंद्रापासून जिल्हा रुग्णालयापर्यंत सातत्यपूर्ण सेवा",
    abhaNotLinked:"ABHA: जोडलेले नाही", selectFacility:"📍 सुविधा निवडा",
    largeText:"A+ मोठा फॉन्ट",
    tabs:{home:"मुख्यपृष्ठ",triage:"तपासणी",queue:"रांग",referral:"रेफरल",map:"नकाशा",meds:"औषध",dash:"डॅशबोर्ड"},
    home:{eyebrow:"स्वागत आहे", title:"आज तुम्हाला काय हवे आहे?",
      linkAbha:"तुमचा ABHA ID जोडा", abhaPh:"14 अंकी ABHA क्रमांक",
      village:"तुमची जवळची सुविधा", link:"जोडा आणि पुढे जा",
      tiles:{triage:["🩺","लक्षणे तपासा","बोला किंवा लिहा"],
             video:["📹","व्हिडिओ सल्ला","डॉक्टरांशी बोला"],
             queue:["🎫","बुक करा / रांग","प्रवास टाळा"],
             referral:["🔗","माझा रेफरल","केस ट्रॅक करा"],
             map:["🗺️","सुविधा नकाशा","जवळचे केंद्र शोधा"],
             meds:["💊","औषध तपासा","स्टॉकमध्ये आहे का?"],
             followup:["❤️‍🩹","फॉलो-अप","माता / बालक / जुनाट आजार"]},
      recent:"अलीकडील क्रियाकलाप", noActivity:"या सत्रात अद्याप कोणतीही क्रिया नाही."},
    triage:{eyebrow:"डिजिटल ट्रायएज", title:"काय त्रास आहे ते सांगा",
      voiceLabel:"तुमची समस्या बोला (मराठी, हिंदी किंवा इंग्रजी)",
      voicePlaceholder:"माइक दाबा आणि बोला, किंवा इथे टाइप करा...",
      listening:"ऐकत आहोत… आता बोला", notSupported:"या ब्राउझरमध्ये आवाज इनपुट उपलब्ध नाही. कृपया टाइप करा.",
      detected:"आम्ही ऐकले:", autoSelected:"तुमच्या आवाजावरून आपोआप निवडले:",
      symptomsLbl:"लक्षणे निवडा (एकाहून अधिक निवडता येतील)", durationLbl:"हे किती काळापासून आहे?",
      severityLbl:"किती तीव्र वाटते? (1=सौम्य, 5=सर्वाधिक)", ageLbl:"वय", ageGroupLbl:"वयोगट",
      submit:"तपासा", result:"तपासणी निकाल",
      low:"कमी धोका — घरगुती काळजी पुरेशी", med:"मध्यम धोका — टेलीकन्सल्ट सुचवले आहे",
      high:"उच्च धोका — त्वरित सुविधेला भेट द्या / आपत्कालीन",
      lowBody:"घरी काळजी आणि निरीक्षण पुरेसे असावे. लक्षणे वाढल्यास पुन्हा तपासा.",
      medBody:"24 तासांच्या आत PHC वैद्यकीय अधिकाऱ्यासोबत टेलीकन्सल्ट बुक करा.",
      highBody:"याकडे तातडीने लक्ष देण्याची गरज असू शकते. आम्ही हे आपत्कालीन एस्केलेशनसाठी नोंदवले आहे.",
      bookConsult:"आत्ता टेलीकन्सल्ट बुक करा", escalate:"जवळच्या सुविधेला कळवा",
      readAloud:"🔊 निकाल ऐका",
      durations:["<1 दिवस","1-3 दिवस","4-7 दिवस",">1 आठवडा"],
      groups:["बालक (0-12)","किशोर (13-18)","प्रौढ (19-59)","ज्येष्ठ (60+)"]},
    queue:{eyebrow:"अपॉइंटमेंट व रांग", title:"स्लॉट बुक करा, रांग टाळा",
      facility:"सुविधा", dept:"विभाग", slot:"पसंतीची वेळ",
      book:"अपॉइंटमेंट बुक करा", live:"लाइव्ह रांग स्थिती", token:"तुमचा टोकन",
      wait:"अंदाजे प्रतीक्षा", position:"रांगेतील स्थान"},
    referral:{eyebrow:"सातत्यपूर्ण सेवा", title:"तुमचा रेफरल प्रवास",
      note:"हा धागा तुमची केस सुविधांदरम्यान फिरत असताना ट्रॅक करतो, जेणेकरून कोणताही रेकॉर्ड हरवणार नाही."},
    map:{eyebrow:"सुविधा नकाशा", title:"तुमच्या जवळची आरोग्य केंद्रे",
      legend:"चिन्हे", tapHint:"तपशील, अंतर आणि त्वरित कृतीसाठी मार्करवर टॅप करा.",
      subCentre:"उपकेंद्र", phc:"PHC", ruralHospital:"ग्रामीण रुग्णालय", districtHospital:"जिल्हा रुग्णालय",
      viewQueue:"बुक करा / रांग पहा", viewMeds:"औषध साठा तपासा", coordinates:"निर्देशांक"},
    meds:{eyebrow:"निदान व औषधालय", title:"औषध व चाचणी उपलब्धता",
      search:"औषध किंवा चाचणी शोधा", nearby:"जवळच्या सुविधा"},
    dash:{eyebrow:"सुविधा डॅशबोर्ड", title:"आजची स्थिती",
      staffToggle:"कर्मचारी / प्रशासन दृश्य", triaged:"तपासलेले रुग्ण", highRisk:"उच्च-धोका प्रलंबित",
      referralRate:"रेफरल पूर्णता", stockouts:"कमी/संपलेली औषधे",
      followupList:"उच्च-धोका फॉलो-अप्स देय", contacted:"संपर्क केले असे चिन्हांकित करा"},
    sos:{title:"आपत्कालीन एस्केलेशन", body:"हे जवळच्या सुविधेला आणि रुग्णवाहिकेला (108) आपत्कालीन इशारा पाठवण्याचे अनुकरण करते.",
      nearest:"जवळची सुविधा", call:"108 वर कॉल करा (रुग्णवाहिका)", alert:"सुविधा इशारा पाठवा", cancel:"रद्द करा"},
    toastLinked:"ABHA जोडले. सातत्यपूर्ण नोंद सक्रिय.",
    toastBooked:"अपॉइंटमेंट बुक झाली — टोकन",
    toastAlert:"आपत्कालीन इशारा सुविधेला पाठवला ✓",
    toastContacted:"संपर्क केले असे चिन्हांकित",
    micDenied:"मायक्रोफोन परवानगी नाकारली. कृपया टाइप करा."
  }
};
